require("dotenv").config();
const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

app.post("/analyze", async (req, res) => {
    const{ text } = req.body;

    if(!text) {
        return res.status(400).json({ error: "No text provided" });
    }
    try{
        const response = await fetch(`https://generativeLanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,{
            method: "POST",
            headers: {
                "Content-Type": "application/json"},
            body: JSON.stringify({
                contents: [{
                    parts: [{
                        text: `Summarize this Terms and Conditions into exactly 3 concise bullet points highlighting the most important things a user should know. Reply with only the 3 bullets, nothing else.\n\n${text}`
                    }]
                }]
            })
        });

        const data = await response.json();
       
        if (!data.candidates || data.candidates.length === 0) {
            return res.status(500).json({ bullets: null, error: "No content generated by the model." });
        }
        
        const rawText = data.candidates[0].content.parts[0].text;
        const bullets = rawText.split("\n").filter(line => line.trim() !== ""); //split by new line and remove empty lines

        res.json({bullets: bullets, error: null });
        
    } catch(error) {
        console.error("CAUGHT ERROR:", error.message);
        res.status(500).json({ bullets: null, error: error.message || "An error occurred while summarizing." });
    }

});
app.listen(3000, () => {
    console.log("Server running on port 3000");
});